---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Install ansible support packages
      package:
        name:
          - ca-certificates
        state: present
      when: ansible_os_family == 'Debian'
