---

scenario:
  name: layouts

driver:
  name: docker

dependency:
  name: galaxy

platforms:
  - name: instance1
    image: paulfantom/ubuntu-molecule:18.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - minio

  - name: instance2
    image: paulfantom/ubuntu-molecule:18.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - minio

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    diff: True
    v: True
  playbooks:
    create: ../resources/create.yml
    destroy: ../resources/destroy.yml
    prepare: ../resources/prepare.yml

lint:
  name: yamllint

verifier:
  name: testinfra
  options:
    vvv: True
    s: true
  additional_files_or_dirs:
    - ../resources/tests/
  lint:
    name: flake8
