---

- name: reload minio systemd
  systemd:
    name: "{{ _minio_service_name }}"
    daemon_reload: True

- name: restart minio
  service:
    name: "{{ _minio_service_name }}"
    state: restarted
